const SOCKET_ACT = {};

SOCKET_ACT.NEW_INTANT_POST = "NEW_INTANT_POST";
SOCKET_ACT.CANCEL_POST = "CANCEL_POST";
SOCKET_ACT.NEW_NOTIFICATION = "NEW_NOTIFICATION";
SOCKET_ACT.NEW_MESSAGE = "NEW_MESSAGE";

export default SOCKET_ACT;