const SOCKET_ACT = {};

SOCKET_ACT.NEW_INTANT_POST = "NEW_INTANT_POST";
SOCKET_ACT.CANCEL_POST = "CANCEL_POST";
SOCKET_ACT.NEW_NOTIFICATION = "NEW_NOTIFICATION";
SOCKET_ACT.NEW_MESSAGE = "NEW_MESSAGE";
SOCKET_ACT.NEW_MESSAGE_ON_LIST_ITEM = "NEW_MESSAGE_ON_LIST_ITEM";
SOCKET_ACT.NEW_MESSAGE_ON_MESSAGE_DETAIL = "NEW_MESSAGE_ON_LIST_ITEM";

export default SOCKET_ACT;