const HTTP_STATUS_CODE = {};

// Informational responses (100–199)
HTTP_STATUS_CODE.CONTINUE = 100;
HTTP_STATUS_CODE.SWITCH_PROTOCOLS = 101;
HTTP_STATUS_CODE.PROCESSING = 102;
HTTP_STATUS_CODE.EARLY_HINTS = 103;

// Successful responses (200–299)
HTTP_STATUS_CODE.OK = 200;
HTTP_STATUS_CODE.CREATED = 201;
HTTP_STATUS_CODE.ACCEPTED = 202;
HTTP_STATUS_CODE.NON_AUTH_INFO = 203;
HTTP_STATUS_CODE.NO_CONTENT = 204;
HTTP_STATUS_CODE.RESET_CONTENT = 205;
HTTP_STATUS_CODE.PARTIAL_CONTENT = 206;

// Redirection messages (300–399)
HTTP_STATUS_CODE.MULTI_CHOICES = 300;
HTTP_STATUS_CODE.MOVED_PERMANENTLY = 301;
HTTP_STATUS_CODE.FOUND = 302;
HTTP_STATUS_CODE.SEE_OTHER = 303;
HTTP_STATUS_CODE.NOT_MODIFIED = 304;
HTTP_STATUS_CODE.TEMPORARY_REDIRECT = 307;
HTTP_STATUS_CODE.PERMANENT_REDIRECT = 308;

// Client error responses (400–499)
HTTP_STATUS_CODE.BAD_REQUEST = 400;
HTTP_STATUS_CODE.UNAUTHORIZED = 401;
HTTP_STATUS_CODE.PAYMENT_REQUIRED = 402;
HTTP_STATUS_CODE.FORBIDDEN = 403;
HTTP_STATUS_CODE.NOT_FOUND = 404;
HTTP_STATUS_CODE.METHOD_NOT_ALLOWED = 405;
HTTP_STATUS_CODE.NOT_ACCEPTABLE = 406;
HTTP_STATUS_CODE.REQUEST_TIMEOUT = 408;
HTTP_STATUS_CODE.CONFLICT = 409;
HTTP_STATUS_CODE.GONE = 410;
HTTP_STATUS_CODE.LENGTH_REQUIRED = 411;
HTTP_STATUS_CODE.PRECONDITION_FAILED = 412;
HTTP_STATUS_CODE.PAYLOAD_TOO_LARGE = 413;
HTTP_STATUS_CODE.URI_TOO_LONG = 414;
HTTP_STATUS_CODE.UNSUPPORTED_MEDIA_TYPE = 415;
HTTP_STATUS_CODE.RANGE_NOT_SATISFIABLE = 416;
HTTP_STATUS_CODE.EXPECTATION_FAILED = 417;
HTTP_STATUS_CODE.UPGRADE_REQUIRED = 426;
HTTP_STATUS_CODE.PRECONDITION_REQUIRED = 428;
HTTP_STATUS_CODE.TOO_MANY_REQUEST = 429;
HTTP_STATUS_CODE.REQUEST_HEADER_FIELD_TOO_LARGE = 431;
HTTP_STATUS_CODE.UNAVAILABLE_FOR_LEGAL_REASONS = 451;

// Server error responses (500–599)
HTTP_STATUS_CODE.INTERNAL_SERVER_ERROR = 500;
HTTP_STATUS_CODE.NOT_IMPLEMENTED = 501;
HTTP_STATUS_CODE.BAD_GATEWAY = 502;
HTTP_STATUS_CODE.SERVICE_UNVAILABLE = 503;
HTTP_STATUS_CODE.GATEWAY_TIMEOUT = 504;
HTTP_STATUS_CODE.HTTP_VERSION_NOT_SUPPORTED = 505;
HTTP_STATUS_CODE.VARIANT_ALSO_NEGOTIATES = 506;
HTTP_STATUS_CODE.NOT_EXTENDED = 510;
HTTP_STATUS_CODE.NETWORK_AUTHENTICATION_REQUIRED = 511;

export default HTTP_STATUS_CODE;